services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tattler_network

  ffmpeg_extraction_job:
    build: ./services/ffmpeg_extraction_job
    environment:
      VIDEO_FILE: ${VIDEO_FILE:-cars.mp4}
    volumes:
      - ./videos:/app/videos
      - raw_frames_data:/app/raw_frames
    networks:
      - tattler_network

  vehicle_detection_service:
    build: ./services/vehicle_detection_service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      YOLO_CONFIG_DIR: /tmp
      ULTRALYTICS_OFFLINE: 1
    volumes:
      - raw_frames_data:/app/raw_frames  # Read-write access needed to move/delete frames
      - detected_frames_data:/app/detected_frames
      - vehicle_crops_data:/app/vehicle_crops
    depends_on:
      - redis
    networks:
      - tattler_network

  plate_recognition_service:
    build: ./services/plate_recognition
    environment:
      CONFIDENCE_THRESHOLD: ${CONFIDENCE_THRESHOLD:-0.3}
    volumes:
      - vehicle_crops_data:/app/vehicle_crops:ro  # Read-only access to vehicle crops
      - plate_crops_data:/app/plate_crops
      - plate_results_data:/app/results
    depends_on:
      - vehicle_detection_service
    networks:
      - tattler_network

volumes:
  redis_data:
    driver: local
  raw_frames_data:
    driver: local
  detected_frames_data:
    driver: local
  vehicle_crops_data:
    driver: local
  plate_crops_data:
    driver: local
  plate_results_data:
    driver: local

networks:
  tattler_network:
    driver: bridge
